[2022-12-25T16:41:20.078+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ETL_toll_data.unzip_data manual__2022-12-25T16:41:18.303316+00:00 [queued]>
[2022-12-25T16:41:20.101+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ETL_toll_data.unzip_data manual__2022-12-25T16:41:18.303316+00:00 [queued]>
[2022-12-25T16:41:20.101+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T16:41:20.102+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2022-12-25T16:41:20.102+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T16:41:20.141+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): unzip_data> on 2022-12-25 16:41:18.303316+00:00
[2022-12-25T16:41:20.142+0000] {base_task_runner.py:129} INFO - Running on host: 8fd7e45d4638
[2022-12-25T16:41:20.142+0000] {base_task_runner.py:130} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'unzip_data', 'manual__2022-12-25T16:41:18.303316+00:00', '--job-id', '288', '--raw', '--subdir', 'DAGS_FOLDER/toll_data_etl.py', '--cfg-path', '/tmp/tmpzjytxyia']
[2022-12-25T16:41:23.674+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data /home/***/.local/lib/python3.7/site-packages/***/plugins_manager.py:258 RemovedInAirflow3Warning: This decorator is deprecated.
[2022-12-25T16:41:23.675+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data 
[2022-12-25T16:41:23.676+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data In previous versions, all subclasses of BaseOperator must use apply_default decorator for the `default_args` feature to work properly.
[2022-12-25T16:41:23.676+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data 
[2022-12-25T16:41:23.677+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data In current version, it is optional. The decorator is applied automatically using the metaclass.
[2022-12-25T16:41:23.677+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data 
[2022-12-25T16:41:24.265+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data [[34m2022-12-25 16:41:24,264[0m] {[34mdagbag.py:[0m538} INFO[0m - Filling up the DagBag from /opt/***/dags/toll_data_etl.py[0m
[2022-12-25T16:41:25.572+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data [[34m2022-12-25 16:41:25,572[0m] {[34mtask_command.py:[0m389} INFO[0m - Running <TaskInstance: ETL_toll_data.unzip_data manual__2022-12-25T16:41:18.303316+00:00 [running]> on host 8fd7e45d4638[0m
[2022-12-25T16:41:25.744+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=bala@yopmail.com
AIRFLOW_CTX_DAG_OWNER=bala
AIRFLOW_CTX_DAG_ID=ETL_toll_data
AIRFLOW_CTX_TASK_ID=unzip_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-25T16:41:18.303316+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-25T16:41:18.303316+00:00
[2022-12-25T16:41:25.746+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-25T16:41:25.747+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DB0250EN-SkillsNetwork/labs/Final%20Assignment/tolldata.tgz &&  tar zxvf tolldata.tgz -C ./data']
[2022-12-25T16:41:25.759+0000] {subprocess.py:86} INFO - Output:
[2022-12-25T16:41:25.780+0000] {subprocess.py:93} INFO - --2022-12-25 16:41:25--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DB0250EN-SkillsNetwork/labs/Final%20Assignment/tolldata.tgz
[2022-12-25T16:41:26.152+0000] {subprocess.py:93} INFO - Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.45.118.108
[2022-12-25T16:41:26.460+0000] {subprocess.py:93} INFO - Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.45.118.108|:443... connected.
[2022-12-25T16:41:27.485+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 200 OK
[2022-12-25T16:41:27.485+0000] {subprocess.py:93} INFO - Length: 528994 (517K) [application/x-tar]
[2022-12-25T16:41:27.486+0000] {subprocess.py:93} INFO - Saving to: â€˜tolldata.tgzâ€™
[2022-12-25T16:41:27.486+0000] {subprocess.py:93} INFO - 
[2022-12-25T16:41:28.100+0000] {subprocess.py:93} INFO -      0K .......... .......... .......... .......... ..........  9% 81.3K 6s
[2022-12-25T16:41:28.408+0000] {subprocess.py:93} INFO -     50K .......... .......... .......... .......... .......... 19%  162K 4s
[2022-12-25T16:41:28.711+0000] {subprocess.py:93} INFO -    100K .......... .......... .......... .......... .......... 29%  165K 3s
[2022-12-25T16:41:28.714+0000] {subprocess.py:93} INFO -    150K .......... .......... .......... .......... .......... 38% 12.6M 2s
[2022-12-25T16:41:29.260+0000] {subprocess.py:93} INFO -    200K .......... .......... .......... .......... .......... 48% 91.6K 2s
[2022-12-25T16:41:29.264+0000] {subprocess.py:93} INFO -    250K .......... .......... .......... .......... .......... 58% 14.2M 1s
[2022-12-25T16:41:29.265+0000] {subprocess.py:93} INFO -    300K .......... .......... .......... .......... .......... 67% 27.5M 1s
[2022-12-25T16:41:29.503+0000] {subprocess.py:93} INFO -    350K .......... .......... .......... .......... .......... 77% 60.4M 1s
[2022-12-25T16:41:29.507+0000] {subprocess.py:93} INFO -    400K .......... .......... .......... .......... .......... 87%  208K 0s
[2022-12-25T16:41:29.514+0000] {subprocess.py:93} INFO -    450K .......... .......... .......... .......... .......... 96% 7.14M 0s
[2022-12-25T16:41:29.514+0000] {subprocess.py:93} INFO -    500K .......... ......                                     100%  130M=2.0s
[2022-12-25T16:41:29.515+0000] {subprocess.py:93} INFO - 
[2022-12-25T16:41:29.515+0000] {subprocess.py:93} INFO - 2022-12-25 16:41:29 (255 KB/s) - â€˜tolldata.tgzâ€™ saved [528994/528994]
[2022-12-25T16:41:29.516+0000] {subprocess.py:93} INFO - 
[2022-12-25T16:41:29.559+0000] {subprocess.py:93} INFO - tar: data: Cannot open: No such file or directory
[2022-12-25T16:41:29.560+0000] {subprocess.py:93} INFO - tar: Error is not recoverable: exiting now
[2022-12-25T16:41:29.560+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-12-25T16:41:29.587+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-12-25T16:41:29.595+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_toll_data, task_id=unzip_data, execution_date=20221225T164118, start_date=20221225T164120, end_date=20221225T164129
[2022-12-25T16:41:29.656+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-12-25T16:41:29.656+0000] {configuration.py:635} WARNING - section/key [smtp/smtp_user] not found in config
[2022-12-25T16:41:29.657+0000] {email.py:229} INFO - Email alerting: attempt 1
[2022-12-25T16:41:29.679+0000] {configuration.py:635} WARNING - section/key [smtp/smtp_user] not found in config
[2022-12-25T16:41:29.679+0000] {email.py:229} INFO - Email alerting: attempt 1
[2022-12-25T16:41:29.680+0000] {taskinstance.py:1835} ERROR - Failed to send email to: ['bala@yopmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1378, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1524, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1585, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2235, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1833, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2237, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2022-12-25T16:41:29.760+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data Traceback (most recent call last):
[2022-12-25T16:41:29.761+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data   File "/home/***/.local/bin/***", line 8, in <module>
[2022-12-25T16:41:29.762+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data     sys.exit(main())
[2022-12-25T16:41:29.763+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/__main__.py", line 39, in main
[2022-12-25T16:41:29.764+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data     args.func(args)
[2022-12-25T16:41:29.765+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 52, in command
[2022-12-25T16:41:29.765+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data     return func(*args, **kwargs)
[2022-12-25T16:41:29.767+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 108, in wrapper
[2022-12-25T16:41:29.767+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data     return f(*args, **kwargs)
[2022-12-25T16:41:29.768+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 396, in task_run
[2022-12-25T16:41:29.769+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data     _run_task_by_selected_method(args, dag, ti)
[2022-12-25T16:41:29.770+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 195, in _run_task_by_selected_method
[2022-12-25T16:41:29.770+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data     _run_raw_task(args, ti)
[2022-12-25T16:41:29.771+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 272, in _run_raw_task
[2022-12-25T16:41:29.772+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data     pool=args.pool,
[2022-12-25T16:41:29.772+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 75, in wrapper
[2022-12-25T16:41:29.773+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data     return func(*args, session=session, **kwargs)
[2022-12-25T16:41:29.774+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1378, in _run_raw_task
[2022-12-25T16:41:29.775+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data     self._execute_task_with_callbacks(context, test_mode)
[2022-12-25T16:41:29.775+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1524, in _execute_task_with_callbacks
[2022-12-25T16:41:29.776+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data     result = self._execute_task(context, task_orig)
[2022-12-25T16:41:29.777+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1585, in _execute_task
[2022-12-25T16:41:29.778+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data     result = execute_callable(context=context)
[2022-12-25T16:41:29.778+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/operators/bash.py", line 197, in execute
[2022-12-25T16:41:29.779+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data     f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
[2022-12-25T16:41:29.780+0000] {base_task_runner.py:116} INFO - Job 288: Subtask unzip_data ***.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-12-25T16:41:30.263+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-25T16:41:30.317+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
